### ISSUE TITLE
Always get the same results

### ISSUE THREAD

**Issue by b2p-fred** [dvdoug/behat-code-coverage#3]
Hi, 
first of all, very thanks for this package !

I am using Behat for testing a Symfony API Platform REST API that I developed. As of now I have 3 tests suites involving ~200 scenarios. Whatever the tests I am running I always get the same results which are:
```
Code Coverage Report:     
  2022-02-05 11:10:25     
                          
 Summary:                 
  Classes:  0.00% (0/8)   
  Methods: 27.27% (15/55) 
  Lines:   11.89% (27/227)

App\Doctrine\DocumentAnnexListener
  Methods:  50.00% ( 2/ 4)   Lines:  18.18% (  4/ 22)
App\Doctrine\DocumentReceivedListener
  Methods:  50.00% ( 2/ 4)   Lines:  12.00% (  3/ 25)
App\Doctrine\DocumentStatusListener
  Methods:  50.00% ( 2/ 4)   Lines:  11.43% (  4/ 35)
App\Doctrine\HashPasswordListener
  Methods:  40.00% ( 2/ 5)   Lines:  16.67% (  4/ 24)
App\Entity\User
  Methods:  14.29% ( 4/28)   Lines:  13.95% (  6/ 43)
App\Repository\ContactRepository
  Methods:  33.33% ( 1/ 3)   Lines:   6.45% (  2/ 31)
App\Repository\DocumentHistoryRepository
  Methods:  50.00% ( 1/ 2)   Lines:  18.18% (  2/ 11)
App\Repository\UserRepository
  Methods:  20.00% ( 1/ 5)   Lines:   5.56% (  2/ 36)

``` 

Any idea about this behaviour ?

Indeed I have more than 10 tested Doctrine 'entites' located in the App\Entity but the only one that is in the report is my User class that is used for login on the API ...

**Comment by b2p-fred** [comment]
I suppose this may help ... some more information about my test environment:
- symfony 6.0
- api-platform 2.6
- behat 3.10
- behat-code-coverage: 5.2.2
- phpunit/php-code-coverage: 9.2.10
- phpunit/phpunit: 9.5
- 
-

**Comment by dvdoug** [comment]
Hello

How are you executing your tests - is it all in-process with the test framework invoking the controller with the relevant parameters, or are your tests making real HTTP calls into another process? It sounds like it might be the second one?

**Comment by b2p-fred** [comment]
Hello
yes it is the second one. I a m starting the Symfony development server which is listening on an HTTP port and I am starting behat in another process.

**Comment by dvdoug** [comment]
The problem you're having is that it's not just enough to have the coverage driver installed, it has to actively be enabled to collect the coverage. This can only be done at runtime.

However, because your test suite and your code are running in separate processes, enabling it during test suite execution (which is what this library does), can only enable it for the code that is running inside Behat, it does not/cannot capture the code that's running inside the other process on the other end of the HTTP call. The coverage data you are seeing is probably just the code that is setting up fixtures etc

You've probably got 2 options.

1) Switch (most?) of the tests to use a simulated HTTP call rather than an actual one. I'm not familiar with API Platform, but I know Symfony itself can do this, e.g. https://symfony.com/doc/current/testing.html#making-requests
2) There is an alternative Behat coverage extension that you might want to look at: https://packagist.org/packages/matthiasnoback/behat-remote-code-coverage-extension that does allow for collecting coverage data from a different process, although setting it up is more complex.

Hope that helps

**Comment by b2p-fred** [comment]
For sure it helps ! Many thanks for this very clear answer. I understand my problem and I will have a look at both of your suggestions. Once again, thanks.
