### ISSUE TITLE
Possible to split branchAndPathCoverage

### ISSUE THREAD

**Issue by Lewiscowles1986** [dvdoug/behat-code-coverage#4]
Hello 👋 

Thank you for this amazing library. I Started using it at work for GitLab coberturra coverage reports. Recently I noticed this Path coverage, and I thought I'd dig in a little more as even with high branch and line coverage, our Path coverage is quite low.

Big Picture, the coders on my team should stop writing long, winding methods. I'm with you; but I'm not sure how practical it is to say "You should have known and not been doing this in the past".

Just found the setting `branchAndPathCoverage`. I like Branch coverage, but would like to disable path coverage. In the worst case scenario I will turn off both branch and path coverage to see if it improves the coverage reports we generate; as other teams are using pcov, which isn't xdebug and so should not be generating path coverage anyhow. But will I lose branch coverage? Is there a possibility to have each of the two independently configurable?

Thanks for your time reading.

**Comment by dvdoug** [comment]
Hi @Lewiscowles1986 

There are different aspects to your question here:

1) This library wraps the php-code-coverage (https://github.com/sebastianbergmann/php-code-coverage/) library that's part of PHPUnit and so the switches that exist here mostly just replicate the switches that are available from there. So any feature requests here, may well need an actioned feature request over there first (this one would)

2) Can you enable branch coverage, but not path coverage? Certainly not currently, the toggle switch only exists because Xdebug has to be explicitly put into a special mode to collect the extra data (because it's slower). This is a single switch of php-code-coverage simply because Xdebug has a single switch too.

3) In theory, each type of report could have a switch added to php-code-coverage (and then here) to only output the branch coverage side of things and skip the path coverage side. However...

4) Having the report say you have low path coverage is not necessarily a bad thing. It's the truth after all, better to know it and accept it rather than lie to yourself? 😜 If you haven't already seen it, my own philosophy is outlined here: https://doug.codes/php-code-coverage#which Plus...

5) Having taken look at the Cobertura output (https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Cobertura.php), it seems to me that it's actually only outputting branch numbers anyway. The complexity number is path-based, but the rest is all branch-based. So I think what you're asking for here is already happening?

**Comment by Lewiscowles1986** [comment]
Thank you 👍  I'll close as it does belong with other libraries and tooling

* xdebug
* php-code-coverage

I Don't disagree with you on the metrics. It's more that I wanted to turn it off for now, as it distracts me reading the reports. At first, I thought coverage was broken. It's just an example right-now of poorly written code that needs to be chopped a bit.
